### ISSUE TITLE
Paintbrush not working

### ISSUE THREAD

**Issue by stormykara** [MapperTV/roadstuff#15]
Hello!

I recently downloaded your most recent version of Road Stuff (version 2.0.8.0 for Minecraft 1.14.4). I understand it's still in the beta phase, and I have some bugs/issues that have arisen.

First, the paintbrush doesn't work on the blocks. I am in creative, I filled a paint bucket with white (and yellow) paint, put paint on the brush, chose a pattern, and left-clicked on both an asphalt and a concrete block. No pattern appeared. I turned off my texture pack just to see if that was messing anything up and it still did not work. I'm currently using Java Edition Minecraft 1.14.4.

The rest of the mod works perfect, I can place blocks with lines on them using the /fill command, but that is tedious. One other thing, and this may be fixed with the paintbrush, how do I rotate the lines/numbers/letters on the blocks to face the way I want? If I paint them with the paintbrush, will it automatically orient itself to face me, or do they always face in the same direction?

Thank you, and I really like this mod! It's easy and simple, but has a lot of versatility.

**Comment by MapperTV** [comment]
Hello,

You'll have to provide more information as I can't replicate the problem: which Forge version is used, if you use other mods as well etc. Did you also tried in survival?

The paintbrush will paint using your orientation but you can rotate the line if you click again on the block. Also using the brush with the other hand inverts the rotation.

**Comment by MapperTV** [comment]
Did you actually say Forge 28.0.22? This version is almost 3 months old, and won't work with the current version of Road Stuff as the left click event needed for the paintbrush wasn't back yet. Please update Forge and check again.

**Comment by stormykara** [comment]
My apologies, I did not realize that I needed to update Forge. It works fine now.

Thank you for your quick replies.
