### ISSUE TITLE
Using a non supported dye on a paint bucket still consumes the dye

### ISSUE THREAD

**Issue by BrisingrAerowing** [MapperTV/roadstuff#19]
**FILL THIS!**
• Minecraft version: 1.14.4
• Forge version: 28.1.107
• Road Stuff version: 2.1.0
• Other mods used or modpack: Lots. Will get a list.

**Describe the bug**
Using an unsupported dye (e.g. red) on a paint bucket will consume the dye, even though the bucket isn't filling up,

**Comment by MapperTV** [comment]
Thanks for the report. It's just a missing condition, easy to fix.
