### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by TheEpicness9000** [MapperTV/roadstuff#20]
Do you have a Discord? If so, a user making a similar mod, CSX8600 with their Traffic Control mod, could use help.

**Comment by MapperTV** [comment]
I know, we already discussed once as he asked to implement some of my contents into his mod (which I agreed). As I can see the mods are still in 1.12 and 1.14/1.15 versions are completely different, especially 1.15 that completely change rendering. 1.12 code is almost useless now, it needs major rewrite. And I'm already rewriting my sign from scratch, I just paused it waiting for 1.15.

**Comment by TheEpicness9000** [comment]
Do you know the meanings of the signs used in your mod? I am making a document so CSX can title the respective signs properly.

**Comment by MapperTV** [comment]
You can find information here:

https://en.wikipedia.org/wiki/Comparison_of_European_road_signs
https://en.wikipedia.org/wiki/Comparison_of_MUTCD-influenced_traffic_signs
