### ISSUE TITLE
Some suggestions: Asphalt/Concrete Signs; Slab Shifted White/Yellow Lines

### ISSUE THREAD

**Issue by Skkubah** [MapperTV/roadstuff#8]
Suggestions:
- More signs for the asphalt road, like: SLOW (SL-OW), TURN (TU-RN), LEFT (LE-FT), RIGHT (???), ... ;
 - What about numbers and letters signs (they would be larger than the letters used in the signs);
- Road signs for both the asphalt and concrete roads;
For now, this is all I have in my mind.

**Comment by KillerMapper** [comment]
Hi,

I had more words planned and will eventually be in 1.9+ versions. For letters and numbers, that should be done one day as well.
I'm not sure what do you mean about road signs for roads. Do you mean painted signs on the floor?

Thanks for your suggestions.

**Comment by Skkubah** [comment]
Yes, it would be the painted signs on the floor, like the "EXIT" and "STOP" ones. It would be nice if they were available for both concrete and asphalt roads.

**Comment by Skkubah** [comment]
Greetings,

Recently, while building a road using this mod, I've noticed that there isn't any Slab with Shifted White/Yellow Lines.
![2017-01-19_22 32 30](https://cloud.githubusercontent.com/assets/10351506/22131258/2e15e22e-de99-11e6-978a-13d4c0762e63.png)

Thank you for your time.
